apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bb8i
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0065-tenant/tkrw-pr712-0075-0065-app/devfile-sample-bb8i@sha256:e0e9844fe6f131b10316ac49792a5c7fcee8332068569f21de14792a82a65c57
        name: my-nodejs
        resources: {}
status: {}
